import type { ITheme } from '@xterm/xterm';
import type { Theme } from '$lib/stores/theme.svelte';

/** xterm palettes aligned with the Linear design tokens (see lib/styles/tokens.css). */
export const xtermThemes: Record<Theme, ITheme> = {
  dark: {
    background: '#0f1011',
    foreground: '#d0d6e0',
    cursor: '#f7f8f8',
    cursorAccent: '#0f1011',
    selectionBackground: '#5e6ad24d',
    black: '#1b1c1f',
    red: '#eb5757',
    green: '#4cb782',
    yellow: '#f2c94c',
    blue: '#7170ff',
    magenta: '#bb87fc',
    cyan: '#4ea7fc',
    white: '#d0d6e0',
    brightBlack: '#62666d',
    brightRed: '#ff7b7b',
    brightGreen: '#6fd6a0',
    brightYellow: '#f7dc7e',
    brightBlue: '#9a99ff',
    brightMagenta: '#d0a9fd',
    brightCyan: '#7fc0fd',
    brightWhite: '#f7f8f8',
  },
  light: {
    background: '#ffffff',
    foreground: '#1b1c1f',
    cursor: '#1b1c1f',
    cursorAccent: '#ffffff',
    selectionBackground: '#5e6ad233',
    black: '#1b1c1f',
    red: '#d93f3f',
    green: '#2d9d6b',
    yellow: '#c58b0c',
    blue: '#4f5bc4',
    magenta: '#8e4ec6',
    cyan: '#2f7fd1',
    white: '#6c6f78',
    brightBlack: '#9a9ca4',
    brightRed: '#e5484d',
    brightGreen: '#30a46c',
    brightYellow: '#d9a21b',
    brightBlue: '#5e6ad2',
    brightMagenta: '#a15dd6',
    brightCyan: '#3b8fe0',
    brightWhite: '#1b1c1f',
  },
};
